### ISSUE TITLE
Implementation: Battle

### ISSUE THREAD

**Issue by JonasKaad** [JonasKaad/SemesterProject-4#211]
Something about battle simulation/view with the event system, etc.

**Comment by VictorABoye** [comment]
There's a small mistake in the state machine flow chart for the battle loop. I couldn't find it on Google Drive, so i've added a comment on Overleaf.

**Comment by VictorABoye** [comment]
+ All diagrams without titles

**Comment by AlexanderNorup** [comment]
@VictorABoye Fixed
