### ISSUE TITLE
Implementation: OSGi

### ISSUE THREAD

**Issue by JonasKaad** [JonasKaad/SemesterProject-4#216]
Write about the component model we're using. i.e. OSGi

- Bundles (Modules)
- Registering (Modules)
- Accessing (Modules) (Dependency Injection)
- Loading/unloading
- Limitations?

**Comment by Gorm2303** [comment]
I have added a few comments to your section in the report.
.bnd file generates -> metadata in the manifest file.
We could mention metadata for each component and .jar files in this section, we have not mentioned it once yet ¯\_(ツ)_/¯
