### ISSUE TITLE
Design: Map

### ISSUE THREAD

**Issue by SebMon** [JonasKaad/SemesterProject-4#218]
IMapView, Entity Framework, SPIs(contracts, pre and post conditions) for the relevant things, etc.

**Comment by JonasKaad** [comment]
Overall looks good, few comments:

In the section about responsibilities, should we also add that it should display/draw the pause menu, summary etc?

I don't know if it's just a hard sentence to read, or if it's missing some words, etc. but perhaps rephrase this line (line 73):
_"Then another class that is extending the IGamePluginService, the concrete Entity is instantiated and the relevant parts for that entity are added. "_

**Comment by VictorABoye** [comment]
> I don't know if it's just a hard sentence to read, or if it's missing some words, etc. but perhaps rephrase this line (line 73): _"Then another class that is extending the IGamePluginService, the concrete Entity is instantiated and the relevant parts for that entity are added. "_

I've updated the sentence to be: _"Then in another
class, that is implementing the IGamePluginService, the concrete Entity is instantiated and the relevant parts for that entity are added"_
